name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Clean web dependencies
        run: |
          rm -rf web/node_modules web/pnpm-lock.yaml
          pnpm install --filter ./web
      - name: Build
        run: pnpm -r run build
      - name: Test
        run: pnpm -r run test
