name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install --no-frozen-lockfile
        run: pnpm install
      - name: Build
        run: pnpm -r run build
      - name: Test
        run: pnpm -r run test
