name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Clean install all dependencies
        run: |
          rm -rf node_modules pnpm-lock.yaml web/node_modules web/pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
      - name: Verify SvelteKit CLI availability
        run: |
          ls -l web/node_modules/.bin
          web/node_modules/.bin/svelte-kit --version
      - name: Build all packages
        run: pnpm -r run build
      - name: Test all packages
        run: pnpm -r run test
